#!/usr/bin/env python3
"""
Downloads Twemoji SVGs for the icons we need, renders 12×12 PNGs
(super-sample 96→12, alpha-threshold), and emits a C++ source file
with the pixel data baked in as constexpr arrays.

Twemoji is licensed CC-BY 4.0 — credit in README.
"""
import io, os, sys, urllib.request
import cairosvg
from PIL import Image

SIZE = 12
SUPERSAMPLE = 96
ALPHA_THRESHOLD = 128

ICONS = [
    ("heart",     "2764"),
    ("cake",      "1f370"),
    ("turkey",    "1f983"),
    ("cat_black", "1f408-200d-2b1b"),
    ("pumpkin",   "1f383"),
    ("tree",      "1f384"),
    ("snowflake", "2744"),
    ("sun",       "2600"),
    ("leaf",      "1f342"),
    ("sprout",    "1f331"),
    ("globe",     "1f30d"),
    ("star",      "2b50"),
    ("party",     "1f389"),
    ("sword",     "1f5e1"),
]

URL = "https://raw.githubusercontent.com/jdecked/twemoji/main/assets/svg/{}.svg"
HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
PNG_DIR = os.path.join(PROJECT, "icons", "special")
GEN_CPP = os.path.join(PROJECT, "src", "render", "special_icons.gen.cpp")

def render(name, codepoint):
    svg = urllib.request.urlopen(URL.format(codepoint), timeout=10).read()
    png = cairosvg.svg2png(bytestring=svg, output_width=SUPERSAMPLE, output_height=SUPERSAMPLE)
    img = Image.open(io.BytesIO(png)).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    px = img.load()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            px[x, y] = (r, g, b, 255) if a >= ALPHA_THRESHOLD else (0, 0, 0, 0)
    img.save(os.path.join(PNG_DIR, f"{name}.png"))
    return img

def to_words(img, name):
    """Return list of 0xRRGGBB ints (alpha encoded in top byte: 0xFF=opaque, 0x00=clear)."""
    px = img.load()
    out = []
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            out.append((a << 24) | (r << 16) | (g << 8) | b)
    return out

def main():
    os.makedirs(PNG_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(GEN_CPP), exist_ok=True)

    all_data = {}
    for name, cp in ICONS:
        img = render(name, cp)
        all_data[name] = to_words(img, name)
        print(f"  {name:14s} OK")

    lines = []
    lines.append("// AUTO-GENERATED by tools/gen_icons.py — do not edit by hand.")
    lines.append("// Icon art from Twemoji (CC-BY 4.0).")
    lines.append('#include "render/special_icons.hpp"')
    lines.append("")
    lines.append("namespace icons {")
    lines.append("")
    for name, _ in ICONS:
        words = all_data[name]
        lines.append(f"static const uint32_t {name.upper()}_PX[{SIZE*SIZE}] = {{")
        for row in range(SIZE):
            chunk = words[row*SIZE:(row+1)*SIZE]
            lines.append("    " + ", ".join(f"0x{w:08X}" for w in chunk) + ",")
        lines.append("};")
        lines.append(f"const SpecialIcon {name.upper()} = {{ {SIZE}, {SIZE}, {name.upper()}_PX }};")
        lines.append("")
    lines.append("}  // namespace icons")
    lines.append("")

    with open(GEN_CPP, "w") as f:
        f.write("\n".join(lines))
    print(f"\nWrote {GEN_CPP}")
    print(f"Wrote PNGs to {PNG_DIR}/")

if __name__ == "__main__":
    main()
